Add beamnrc installation to configure scripts

diff --git a/HEN_HOUSE/scripts/configure b/HEN_HOUSE/scripts/configure
--- a/HEN_HOUSE/scripts/configure
+++ b/HEN_HOUSE/scripts/configure
@@ -688,7 +688,7 @@ if { (eval $test_compile) 2>&5; test_status=$?; (exit $test_status); }; then
       echo >&2 "no (echo returns a non-zero exit status)"
   fi
 else
-  echo >&2 "no (compilation failes)"
+  echo >&2 "no (compilation fails)"
 fi
 
 if test "x$system_is_function" = xyes; then
@@ -706,7 +706,7 @@ if test "x$system_is_function" = xyes; then
       system_is_function=no
     fi
   else
-    echo "no (second compilation fails?)" >&2
+    echo "no (second compilation fails!)" >&2
     system_is_function=no
   fi
 fi
@@ -1093,7 +1093,7 @@ _ACEOF
       echo "no" >&2
     fi
   else
-    echo "no (simple program failed to compile ???)" >&2
+    echo "no (simple program failed to compile!)" >&2
   fi
 #fi
 rm -f conftest.$test_ext conftest$test_exeext
@@ -1577,7 +1577,7 @@ if test ! -d $machine_mortran_dir; then
     printf $format "Creating lib/$conf_name directory ... " >&2
     mkdir -p $machine_mortran_dir
     if test ! -d $machine_mortran_dir; then
-        echo "Failed!" >&2
+        echo "Failed" >&2
         echo "Error was: could not create $machine_mortran_dir" >&2
         exit 1
     fi
@@ -1606,7 +1606,7 @@ if test "x$have_c_compiler" = xyes; then
       echo "OK" >&2
       c_compiler_works=yes
     else
-      echo "failed" >&2
+      echo "Failed" >&2
       cat >&2 <<EOF
 
 Failed to compile egs_c_utils.c. This may be due to a variety of reasons
@@ -1636,7 +1636,7 @@ EOF
         echo "OK" >&2
         have_loadbeamlib=yes
     else
-        echo "failed" >&2
+        echo "Failed" >&2
     fi
     printf $format "Creating load_vculib.o ... " >&2
     echo " ******************** compile load_vculib.c **************" >&5
@@ -1645,7 +1645,7 @@ EOF
         echo "OK" >&2
         vculib_object='$(EGS_LIBDIR)load_vculib.o'
     else
-        echo "failed" >&2
+        echo "Failed" >&2
     fi
     ################################################################
     # test for an argument to see if I'm being run from install_egs
@@ -1675,7 +1675,7 @@ _ACEOF
        echo "OK" >&2
        if test ! "x$EGS_HOME" = x && test -d "$EGS_HOME/bin" && test ! -d "$EGS_HOME/bin/$conf_name"; then
         printf $format "Creating $EGS_HOME/bin/$conf_name ... " >&2
-        mkdir -p $EGS_HOME/bin/$conf_name || { echo "failed" >&2; exit 1; }
+        mkdir -p $EGS_HOME/bin/$conf_name || { echo "Failed" >&2; exit 1; }
         echo "OK" >&2
        fi
     fi
@@ -2320,7 +2320,6 @@ cat >&5 <<EOF
 ********************* Compiling Mortran3 ******************
 EOF
 
-echo >&2
 printf $format "Compiling mortran3 ... " >&2
 if cd $HEN_HOUSE/mortran3 2>&5; then
     rm -f $HEN_HOUSE/bin/$conf_name/mortran3.exe $HEN_HOUSE/bin/$conf_name/mortran3.dat
@@ -2337,15 +2336,15 @@ if cd $HEN_HOUSE/mortran3 2>&5; then
          test_status=$?; (exit $test_status); }; then
         echo "OK" >&2
     else
-        echo "failed" >&2
+        echo "Failed" >&2
         echo "See config.log for the output of make" >&2
         echo "Failed program was '$make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file'" >&5
         exit 1
     fi
     mv -f mortran3.f.orig mortran3.f
 else
-    echo "oops" >&2
-    echo "The Mortran directory does not exist ???" >&2
+    echo "Failed" >&2
+    echo "The Mortran directory does not exist!" >&2
     echo "Something is wrong with your EGSnrc installation" >&2
     echo "Failed to change to $HEN_HOUSE/mortrtran3" >&5
     exit 1
@@ -2357,21 +2356,21 @@ cat >&5 <<EOF
 EOF
 
 printf $format "Compiling pegs4 ... " >&2
-if cd $HEN_HOUSE/pegs4; then
+if cd $HEN_HOUSE/pegs4 2>&5; then
     rm -f "pegs4_$conf_name.f"
     rm -f "$HEN_HOUSE/bin/$conf_name/pegs4.exe"
     if { $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file >&5 2>&5;
          test_status=$?; (exit $test_status); }; then
         echo "OK" >&2
     else
-        echo "failed" >&2
+        echo "Failed" >&2
         echo "See config.log for the output of make" >&2
         echo "Failed program was $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file" >&5
         exit 1
     fi
 else
-    echo "oops" >&2
-    echo "The pegs4 directory does not exist ???" >&2
+    echo "Failed" >&2
+    echo "The pegs4 directory does not exist!" >&2
     echo "Something is wrong with your EGSnrc installation" >&2
     echo "Failed to change to $HEN_HOUSE/pegs4" >&5
     exit 1
@@ -2379,19 +2378,75 @@ fi
 
 cat >&5 <<EOF
 
-********************* Splitting .del files ********************************
+********************* Splitting .density files **************
 EOF
 
 printf $format "Generating .density files ... " >&2
-cd density_corrections || { echo "Failed to cd to density corrections ?"; exit 1; }
+cd $HEN_HOUSE/pegs4/density_corrections || { echo "Failed to cd to density corrections directory!"; exit 1; }
 if { $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file >&5 2>&5;
      test_status=$?; (exit $test_status); }; then
      echo "OK" >&2
      echo "*************************** OK *********************** " >&5
 else
-     echo "Failed ?"
+     echo "Failed"
      echo "*************************** Failed *********************** " >&5
 fi
+
+
+cat >&5 <<EOF
+
+********************* Compiling beam_build ******************
+EOF
+
+printf $format "Compiling beam_build ... " >&2
+if cd $HEN_HOUSE/omega/beamnrc/tools 2>&5; then
+    if { $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file >&5 2>&5;
+         test_status=$?; (exit $test_status); }; then
+        echo "OK" >&2
+    else
+        echo "Failed" >&2
+        echo "Failed program was $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file" >&5
+    fi
+else
+    echo "Failed" >&2
+    echo "The $HEN_HOUSE/omega/beamnrc/tools directory does not exist!" >&2
+    echo "Something is wrong with your EGSnrc installation." >&2
+    echo "Failed to change to $HEN_HOUSE/omega/beamnrc/tools" >&5
+    exit 1
+fi
+
+
+cat >&5 <<EOF
+
+********************* Compiling beamnrc progs ***************
+EOF
+
+for prog in beamdp ctcreate statdose readphsp dosxyz_show addphsp; do
+
+    printf $format "Compiling $prog ... " >&2
+
+    if test $prog = dosxyz_show && test $have_c_compiler = no; then
+        echo "Skipping (no C compiler)" >&2;
+        echo "Skipping (no C compiler)" >&5;
+        continue
+    fi
+
+    if cd "$HEN_HOUSE/omega/progs/$prog" 2>&5; then
+    if { $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file >&5 2>&5;
+         test_status=$?; (exit $test_status); }; then
+            echo "OK" >&2;
+        else
+            echo "Failed" >&2
+            echo "Failed program was $make_prog EGS_CONFIG=$HEN_HOUSE/specs/$conf_file" >&5
+        fi
+    else
+        echo "Failed to change directory to $HEN_HOUSE/omega/progs/$prog" >&2
+        echo "Something is wrong with your EGSnrc installation." >&2
+        echo "Failed to change to $HEN_HOUSE/omega/progs/$prog" >&5
+        exit 1
+    fi
+done
+
 
 #******************************************************************************
 #
