Detect failure to launch pbs job in egs-parallel
Detect pbs jobs that fail to launch in egs-parallel, by looking at the
echoed job pid: quit immediately if it is not an integer. If the first
job fails, subsequent jobs are not launched. Report the failure in the
log. Also adjust the format of a few log messages.

diff --git a/HEN_HOUSE/scripts/egs-parallel-pbs b/HEN_HOUSE/scripts/egs-parallel-pbs
--- a/HEN_HOUSE/scripts/egs-parallel-pbs
+++ b/HEN_HOUSE/scripts/egs-parallel-pbs
@@ -199,9 +199,11 @@ for job in $(seq 1 $nthread); do
     fi
 
     ### launch the job
+    pbscommand="qsub -q $queue $scheduler_options"
     runcommand="$command -b -P $nthread -j $job -f $first"
-    log "$jobstr: SUBMIT $runcommand"
-    jobpid=$(qsub -q $queue $scheduler_options <<EOF
+    log "$jobstr: SUBMIT $pbscommand"
+    log "$jobstr: LAUNCH $runcommand"
+    jobpid=$(eval "$pbscommand" <<EOF
 #!/bin/sh
 #PBS -j eo
 #PBS -e ${basename}_w$job.eo
@@ -235,6 +237,12 @@ if [ $job -eq 1 ]; then
 fi
 EOF
     )
+    if ! [[ "${jobpid%%.*}" =~ ^[0-9]+$ ]] ; then
+        log "FAILED to launch job $job"
+        if [[ "$job" = "1" ]]; then
+            quit $LINENO "FAILED to submit first job"
+        fi
+    fi
     echo $jobpid
 
 done
